### ISSUE TITLE
Plan for sunsetting old version

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#24]
How and when to add message on the old web server that it will be shutting down? Do we include a link in that message to try the new web server? Or do we switch to the new one and have a link that direct users to the old one for a bit?

**Comment by vincerubinetti** [comment]
I feel like since the new app will be ready to use relatively soon, and since I can edit the new app much easier than the old one, we could just replace the old one and link to it in case users have problems or want to see the old UI.
