### ISSUE TITLE
Better error messages for when GCP function fails

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#27]
PyGenePlexus has really good error handling and messaging and it would be good to have some more specific errors returned, at least to the google cloud logs. Probably not best to return specific errors on the web server I imagine.

**Comment by vincerubinetti** [comment]
I think we can close this? In this comment https://github.com/krishnanlab/geneplexus-app-v2/pull/45#issuecomment-2354424030, I was able to see the exact error trace thrown from the cloud function from the frontend console. So I think if the package is raising the exceptions appropriately, those should trickle down to the frontend as well for debugging.
