### ISSUE TITLE
Enable compression in functions

### ISSUE THREAD

**Issue by falquaddoomi** [krishnanlab/geneplexus-app-v2#29]

**Comment by vincerubinetti** [comment]
As best I can tell, Flask doesn't do any compression by default. The recommendation looks like `flask-compress`, but not sure if it will work with the `functions_framework` flavor of flask.
https://github.com/colour-science/flask-compress


Might need to do it manually:
https://stackoverflow.com/questions/30165475/how-to-compress-minimize-size-of-json-jsonify-with-flask-in-python

**Comment by vincerubinetti** [comment]
This seems to work, testing locally:

```python
from flask import current_app as app
from flask_compress import Compress

Compress(app)
```

I'll throw it in my current PR.
