### ISSUE TITLE
Change order and default of parameters

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#42]
Can the order of the networks in choose parameter be from top to bottom; STRING, IMP, BioGRID with STRING being the default> 

Can the order of the Geneset context be from top to bottom Combined, GO, Monarch, DisGeNet with Combined as the default.

**Comment by vincerubinetti** [comment]
Changed:

https://github.com/krishnanlab/geneplexus-app-v2/pull/38/commits/01bc8baa8be6c1e1d2e6c7c77baf303811ee37e0
