### ISSUE TITLE
allow users to upload negatives

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#43]
Have a second spot (maybe mostly hidden) where a user can upload genes that will be forced to be negative in training the model (most genes end up not being involved in training). This will be a little tricky to get right possibly so I imagine will be its own PR down the road.

**Comment by vincerubinetti** [comment]
I'd imagine this would logically just be another textbox like the main "enter genes" one?

I'd put it at the bottom of the "enter genes" section, under a collapsible button like "manual negatives", with a (?) help tooltip that briefly explains what the package will do automatically if no negatives are manually entered.

Would these also get checked in the "check genes" section? I guess I would need to call `/gpz-convert-ids` twice.

**Comment by ChristopherMancuso** [comment]
In a user workflow, it seems like calling `gpz-covert-ids` twice would be needed and you would have to keep track of which is positive and which is negative and upload them both `gpz-ml`. I would then have to change `gpa-ml` to handle this.
