### ISSUE TITLE
add info about what parameters were chosen in results page

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#47]
When looking at some results I couldn't remember if the current results I was looking at was trying in human and being shown for mouse, or if it was something else. I think we will want to display on the results page a summary of the chosen parameters that generated the results.

**Comment by vincerubinetti** [comment]
This is already on the results page:

<img width="1291" alt="Screenshot 2024-09-19 at 12 10 05 PM" src="https://github.com/user-attachments/assets/420a6e29-47e5-48c5-ad82-9ef41cdec402">

**Comment by ChristopherMancuso** [comment]
whoops, I'm an idiot
